on:
    types: [opened]

jobs:
  build:
    steps:
      - uses: gege-circle/github-action@master
        env:
          TOKEN: ${{ github.token }}
          REPOSITORY: ${{ github.repository }}
          EVENT: ${{ toJson(github.event) }}
